python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8001 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8002 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8003 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8004 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8005 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8006 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8007 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8008 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8009 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8010 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8011 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8012 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8013 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8014 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8015 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8016 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8017 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8018 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8019 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8020 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8021 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8022 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8023 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8024 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8025 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8026 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8027 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8028 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8029 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8030 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8031 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8032 0 &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8033 0 & 

